//cac thong bao
module.exports = {
  ERROR_MESSAGE: {
    INDEX: {
      EXIST: "INDEX_EXIST",
      NOT_FOUND: "INDEX_NOT_EXIST",
      EMPTY: "INDEX_EMPTY",
      EMPTY_EXPIRATION_DATE: "EMPTY_EXPIRATION_DATE",
      EMPTY_RENTER: "EMPTY_RENTER",
      EMPTY_CAR_NUMBER: "EMPTY_CAR_NUMBER",
      NOT_STANDARD: "NONSTANDARD_EXPIRATION_DATE"
    }
  },
  SUCCESS_MESSAGE: {
    INDEX: {
      RENTED: "INDEX_RENTED",
      DELETED: "INDEX_DELETED"
    }
  }
};
